import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Action, AuthFrame, Brand, ErrorMessage, Field, styles } from '@/components/auth-ui';
import { useAuth } from '@/context/auth';
import { ApiError } from '@/types';

export default function SignupScreen() {
  const router = useRouter(); const auth = useAuth();
  const [displayName, setDisplayName] = useState(''); const [username, setUsername] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [agreed, setAgreed] = useState(false); const [error, setError] = useState<ApiError | null>(null); const [busy, setBusy] = useState(false);
  async function submit() { if (password !== confirm) { setError(ApiError.fromHttpStatus(400, 'Passwords do not match.')); return; } setBusy(true); setError(null); try { await auth.signup({ display_name: displayName.trim(), username: username.trim(), email: email.trim(), password, password_confirm: confirm, agree_to_terms: agreed }); router.replace('/'); } catch (cause) { setError(cause instanceof ApiError ? cause : ApiError.networkError('Unable to create your account')); } finally { setBusy(false); } }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><ScrollView contentContainerStyle={{ flexGrow: 1 }}><AuthFrame><Brand /><Text style={styles.heading}>Join QueueUp</Text><Text style={styles.subheading}>Create an account, then wait for an admin to approve your league access.</Text><Field label="Display name" value={displayName} onChangeText={setDisplayName} returnKeyType="next" /><Field label="Username" value={username} onChangeText={setUsername} autoCapitalize="none" autoCorrect={false} returnKeyType="next" /><Field label="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" returnKeyType="next" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry returnKeyType="next" /><Field label="Confirm password" value={confirm} onChangeText={setConfirm} secureTextEntry returnKeyType="done" /><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: agreed }} onPress={() => setAgreed(value => !value)} style={styles.checkRow}><View style={[styles.checkbox, agreed && styles.checked]}>{agreed && <Text style={styles.check}>✓</Text>}</View><Text style={styles.checkText}>I agree to the QueueUp Terms of Use and Privacy Policy.</Text></Pressable><ErrorMessage message={error?.message} fieldErrors={error?.fieldErrors} /><Action disabled={busy || !displayName || !username || !email || !password || !confirm || !agreed} onPress={() => void submit()}>{busy ? 'Creating account…' : 'Create account'}</Action><Action secondary onPress={() => router.back()}>Back</Action><Text onPress={() => router.push('/login' as never)} style={styles.link}>Already have an account? Log in</Text></AuthFrame></ScrollView></KeyboardAvoidingView>;
}
