import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, Text, TextInput } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { AdminDateField } from '@/components/admin-date-field';
import { AdminFormShell } from '@/components/admin-form-shell';
import { Action } from '@/components/auth-ui';
import { getStaffCountdowns, saveStaffCountdown } from '@/lib/api';
import { colors } from '@/constants/theme';
function CountdownEditor(){const router=useRouter();const{id}=useLocalSearchParams<{id?:string}>();const[title,setTitle]=useState('');const[target,setTarget]=useState('2026-09-02T12:00');const[active,setActive]=useState(true);const[saving,setSaving]=useState(false);useEffect(()=>{if(id)void getStaffCountdowns().then(r=>{const x=r.countdowns.find(c=>c.id===Number(id));if(x){setTitle(x.title);setTarget(x.target_at);setActive(x.active);}})},[id]);const save=async()=>{setSaving(true);try{await saveStaffCountdown({title,target_at:new Date(target).toISOString(),active},id?Number(id):undefined);Alert.alert('Saved','Countdown saved.');router.back();}catch(e){Alert.alert('Unable to save countdown',e instanceof Error?e.message:'Please try again.');}finally{setSaving(false);}};return <ScrollView contentContainerStyle={{padding:24,gap:16,backgroundColor:colors.background,flexGrow:1}}><Text style={{color:colors.text,fontSize:30,fontWeight:'900'}}>{id?'Edit countdown':'New countdown'}</Text><TextInput value={title} onChangeText={setTitle} placeholder="Title" placeholderTextColor={colors.textMuted} style={{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:12,color:colors.text,padding:16,fontSize:16}}/><AdminDateField label="Target time" value={target} onChangeText={setTarget}/><Pressable onPress={()=>setActive(v=>!v)}><Text style={{color:colors.brandLight,fontWeight:'800',padding:12}}>{active?'Active on Home':'Inactive on Home'} · tap to change</Text></Pressable><Action disabled={saving||!title.trim()||!target} onPress={()=>void save()}>{saving?'Saving…':'Save countdown'}</Action><Action secondary onPress={()=>router.back()}>Cancel</Action></ScrollView>}
export default function CountdownRoute(){return <AdminFormShell title="Countdown"><CountdownEditor /></AdminFormShell>}
